root = "."
tmp_dir = "tmp"

[build]
cmd = "make build"
bin = "tmp/main.exe"
full_bin = "./tmp/main.exe"
include_ext = ["go", "yaml", "yml"]
exclude_dir = ["assets", "tmp", "vendor", "docs"]
exclude_file = []
include_dir = []
delay = 1000 # ms
kill_delay = "500ms"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true