basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: این یک نمونه API با Swagger است
  title: نمونه API
  version: "1.0"
paths:
  /hello:
    get:
      description: این endpoint یک سلام برمی‌گرداند
      produces:
      - application/json
      responses:
        "200":
          description: پیام سلام
          schema:
            type: string
      summary: سلام دنیا
swagger: "2.0"
